spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate  # Tootmises kasuta Flyway'd
    properties:
      hibernate:
        format_sql: false

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.security: INFO
    eKaubandus.eKauplus: INFO