version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      # Spring profiil
      - SPRING_PROFILES_ACTIVE=docker
      # Andmebaasi seaded
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

      # JWT seaded
      - JWT_SECRET=${JWT_SECRET}

      # E-posti seaded
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

      # AWS seaded
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    networks:
      - ekauplus-network

  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ekauplus-network

networks:
  ekauplus-network:
    driver: bridge

volumes:
  postgres-data: